### PR TITLE
checked finish work

### PR DESCRIPTION
**Pull request by Hailyk**
checked finished work, and corrected typo

### CODE REVIEW

**Comment by zachlatta** [comment]
What's the advantage of duplicating the existing issue to the markdown file?

**Comment by Hailyk** [comment]
i am not able to edit the issue so i have to edit form the markdown file

**Comment by zachlatta** [comment]
Ah! My bad.

@jonleung can you add the `Contributors` team to the repo?

**Comment by maxwofford** [comment]
@zachlatta @xeonjake Added

**Comment by zachlatta** [comment]
@xeonjake you can now edit the issue directly :-) gonna go ahead and merge this for now.

**Pull request merged**
